[package]
name = "calculator-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
lazy_static = "1.4.0"
pest = "2.7.4"
pest_derive = "2.7.4"
rustyline = "12.0.0"
