integer = @{ ASCII_DIGIT+ }
number  = @{ integer ~ ("." ~ integer?)? }

unary_minus = { "-" }
primary     = _{ number | "(" ~ expr ~ ")" }
atom        = _{ unary_minus? ~ primary }

bin_op   = _{ add | subtract | multiply | divide | modulo | pow }
add      = { "+" }
subtract = { "-" }
multiply = { "*" }
divide   = { "/" }
modulo   = { "%" }
pow      = { "^" }

expr = { atom ~ (bin_op ~ atom)* }

equation = _{ SOI ~ expr ~ EOI }

WHITESPACE = _{ " " }
